image: registry.gitlab.ics.muni.cz:443/muni-kypo-images/ci-cd-virtual-images/packer:latest

stages:
  - validate
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: &qemu $CI_COMMIT_MESSAGE =~ /qemu/i
    - if: &vbox $CI_COMMIT_MESSAGE =~ /vbox/i

default:
  tags:
    - image-builder

validate:
  stage: validate
  script:
    - packer --version
    - packer validate $NAME.json
  needs: []

.build:
  stage: build
  cache:
    paths:
      - packer_cache
  timeout: 3h
  resource_group: virtual-machine
  needs: ["validate"]

build-qemu:
  extends: .build
  script:
    - packer build -only=qemu $NAME.json
  artifacts:
    paths:
      - target-qemu/*
  only: &only-qemu
    variables:
      - *qemu

build-vbox:
  extends: .build
  script:
    - packer build -only=vbox $NAME.json
  artifacts:
    paths:
      - target-vbox/*
  only: &only-vbox
    variables:
      - *vbox

test-qemu:
  stage: test
  script:   # Changes made to this script need to be manually reflected in the windows template
    - ssh-keygen -f ./id_rsa -N "" -C mykey
    - mkdir -p drive/openstack/latest
    - echo "{\"uuid\":\"d8e02d56-2648-49a3-bf97-6be8f1204f38\", \"public_keys\":{\"mykey\":\"`cat id_rsa.pub`\"}}" > drive/openstack/latest/meta_data.json
    - mkisofs -R -J -V config-2 -o config.img drive/
    - qemu-system-x86_64 -accel kvm -m size=4096 -net nic -net user,hostfwd=tcp::2222-:22 -cdrom config.img target-qemu/* &
    - echo "ssh ansible_user=$DISTRO ansible_port=2222 ansible_host=127.0.0.1 ansible_connection=ssh" > inventory
    - ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook --private-key id_rsa -i inventory --ssh-extra-args "-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s" --timeout=30 -v playbook.yml
  resource_group: virtual-machine
  only: *only-qemu
  needs: ["build-qemu"]

test-vbox:
  stage: test
  script:
    - vagrant box add --name mybox target-vbox/*
    - vagrant up
  resource_group: virtual-machine
  only: *only-vbox
  needs: ["build-vbox"]

deploy-qemu-test:
  stage: deploy
  before_script:
    - VERSION=$CI_COMMIT_SHORT_SHA
  script:
    - openstack image create --file target-qemu/* --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi --property hw_rng_model=virtio --property hw_qemu_guest_agent=yes --property os_require_quiesce=yes --property os_type=$TYPE --property os_distro=$DISTRO --property owner_specified.openstack.version=$VERSION $CI_PROJECT_NAME-$VERSION
  when: manual
  only: *only-qemu
  needs: ["build-qemu"]
  variables:
    OS_AUTH_TYPE: "v3applicationcredential"
    OS_AUTH_URL: "https://identity.cloud.muni.cz/v3"
    OS_IDENTITY_API_VERSION: "3"
    OS_INTERFACE: "public"
    OS_REGION_NAME: "brno1"

deploy-qemu-master:
  extends: deploy-qemu-test
  before_script:
    - test ! -z "$VERSION"
  script:  # openstack-deploy is also a few lines above in deploy-qemu-test, but it does not have the --community
   - &openstack-deploy openstack image create --file target-qemu/* --property hw_scsi_model=virtio-scsi --property hw_disk_bus=scsi --property hw_rng_model=virtio --property hw_qemu_guest_agent=yes --property os_require_quiesce=yes --property os_type=$TYPE --property os_distro=$DISTRO --property owner_specified.openstack.version=$VERSION --community $CI_PROJECT_NAME-$VERSION
   - if openstack image show $CI_PROJECT_NAME > /dev/null; then  # Previous image version exists
   -   PREV_VERSION=$(openstack image show $CI_PROJECT_NAME | grep owner_specified.openstack.version | sed -r "s/.*owner_specified.openstack.version='([a-zA-Z0-9.]*)'.*/\1/") || true
   -   if [ -z "$PREV_VERSION" ]; then PREV_VERSION=0.1.0; fi
   -   if openstack image show $CI_PROJECT_NAME-$PREV_VERSION > /dev/null; then
   -     openstack image delete $CI_PROJECT_NAME || openstack image set $CI_PROJECT_NAME --name $CI_PROJECT_NAME-DEPRECATED
   -   else
   -     openstack image set $CI_PROJECT_NAME --name $CI_PROJECT_NAME-$PREV_VERSION
   -   fi
   - fi
   - openstack image set $CI_PROJECT_NAME-$VERSION --name $CI_PROJECT_NAME
   - *openstack-deploy
   - git config user.name "$GITLAB_USER_NAME"; git config user.email "$GITLAB_USER_EMAIL"
   - git tag -a "qemu-$VERSION" -m "Qemu version $VERSION"
   - git push --tags http://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:master
  needs: ["build-qemu", "test-qemu"]
  only:
    refs:
      - master

deploy-vbox:
  stage: deploy
  script:
    - test ! -z "$VERSION"
    - curl --header "Content-Type:application/json" --header "Authorization:Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/box/$VAGRANT_CLOUD_USER/$CI_PROJECT_NAME/versions --data "{\"version\":{\"version\":\"$VERSION\",\"description\":\"$DESCRIPTION\"}}"
    - curl --header "Content-Type:application/json" --header "Authorization:Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/box/$VAGRANT_CLOUD_USER/$CI_PROJECT_NAME/version/$VERSION/providers  --data "{\"provider\":{\"checksum\":\"`sha1sum target-vbox/* | awk '{print $1}'`\",\"checksum_type\":\"sha1\",\"name\":\"virtualbox\"}}"
    - UPLOAD_PATH=$(curl --header "Authorization:Bearer $VAGRANT_CLOUD_TOKEN" https://app.vagrantup.com/api/v1/box/$VAGRANT_CLOUD_USER/$CI_PROJECT_NAME/version/$VERSION/provider/virtualbox/upload | jq -r .upload_path)
    - curl $UPLOAD_PATH --request PUT --upload-file target-vbox/*
    - git config user.name "$GITLAB_USER_NAME"; git config user.email "$GITLAB_USER_EMAIL"
    - git tag -a "vbox-$VERSION" -m "VBox version $VERSION"
    - git push --tags http://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:master
  when: manual
  needs: ["build-vbox", "test-vbox"]
  only:
    refs:
      - master
    variables:
      - *vbox
  variables:
    VAGRANT_CLOUD_USER: "munikypo"
    DESCRIPTION: "placeholder"
